package:
  format-version: "1.0.0"
  name: "net_apps_pic32mx"
  version: "v3.9.0"
  type: "application"
  status: "production"
  
  dependencies:
    - name: "core"
      type: "package"
      version: "v3.13.3"
    - name: "csp"
      type: "package"
      version: "v3.18.2"
    - name: "bsp"
      type: "package"
      version: "v3.17.0"
    - name: "crypto"
      type: "package"
      version: "v3.8.1"
    - name: "net"
      type: "package"
      version: "v3.11.1"
    - name: "wolfssl"
      type: "package"
      version: "v5.4.0"
    - name: "CMSIS-FreeRTOS"
      type: "package"
      version: "v10.5.1"