configName: pic32mx_eth_sk2_freertos
folderName: ''
format_version: v1.0
frameworkPath: ../../..
processor: PIC32MX795F512L
projectName: ''
settings:
  PackageFilter: aws_cloud;bootloader;bsp;core;crypto;csp;ethercat;net;net;net;net;net;net;net;usb;wireless;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: ALL
  DFPPath: .\dev_packs\Microchip\PIC32MX_DFP\1.5.259\atdf\PIC32MX795F512L.atdf
